function Mappe1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MAPPE1 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  MAPPE1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  MAPPE1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Mappe1 = importfile("C:\Users\Marvin\Documents\TRNSYS2020\DATA\Mappe1.xlsx", "Tabelle1", [4, 9]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Oct-2020 13:05:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [4, 9];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["X", "Y", "Z"];
opts.SelectedVariableNames = ["X", "Y", "Z"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
Mappe1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Mappe1 = [Mappe1; tb]; %#ok<AGROW>
end

end