function Aufgabe3vergleich = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  AUFGABE3VERGLEICH = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  AUFGABE3VERGLEICH = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  AUFGABE3VERGLEICH = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Aufgabe3vergleich = importfile("C:\Users\Marvin\Documents\TRNSYS2020\DATA\Aufgabe3vergleich.xlsx", "Tabelle1", [2, 674]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Oct-2020 13:51:39

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 674];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":E" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["TIME", "SimOutlet20", "SimOutlet60", "Outlet20", "Outlet60"];
opts.SelectedVariableNames = ["TIME", "SimOutlet20", "SimOutlet60", "Outlet20", "Outlet60"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
Aufgabe3vergleich = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":E" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Aufgabe3vergleich = [Aufgabe3vergleich; tb]; %#ok<AGROW>
end

end